/**
 * Deterministic handoff contracts (docs/ade/08 §3). The brief is generated by
 * code — never by a model — so identical inputs produce identical bytes.
 */

export type HandoffReason =
  /** Same thread switched to a different harness. */
  | 'harness-switch'
  /** Native session invalidated (route/capability/history change or failed resume). */
  | 'rebase'
  /** Manager dispatched a worker; first context handoff (08 §6). */
  | 'worker-dispatch'
  /** Harness context overflowed; a fresh native session carries on (08 §7). */
  | 'context-overflow'

export type HandoffBudgets = {
  /** How many trailing turns keep their verbatim text. */
  recentTurns: number
  /** Per-message character cap inside the verbatim section. */
  recentTextCap: number
  /** Total character budget for the digest section; oldest lines drop first. */
  digestBudget: number
  /** Per-line character cap inside the digest section. */
  digestLineCap: number
  /** Max commands listed in the work-state section. */
  commandLimit: number
  /** Whole-brief cap in UTF-8 bytes. */
  totalCap: number
}

export const DEFAULT_HANDOFF_BUDGETS: HandoffBudgets = {
  recentTurns: 4,
  recentTextCap: 2_000,
  digestBudget: 3_000,
  digestLineCap: 120,
  commandLimit: 10,
  totalCap: 12 * 1_024
}

/** Numbers surfaced by the `handoff_injected` marker event (08 §4). */
export type HandoffStats = {
  recentTurns: number
  digestLines: number
  files: number
  commands: number
  bytes: number
}

/** The durable "work site" facts extracted from history (08 §3.3). */
export type WorkState = {
  /** Files changed by file_change tool calls ∪ task-workspace changedFiles. */
  files: string[]
  /** command_execution calls, newest last, capped by the caller. */
  commands: Array<{ command: string; exitCode?: number }>
  /** Unfinished todo contents from the latest todo_write call. */
  todos: string[]
  /** Text of the latest active goal, when one exists. */
  goal?: string
  /** Path of the latest approved plan file, when one exists. */
  plan?: string
}
