/**
 * Remote invoke allowlist: browser clients may only reach these IPC channels.
 * Everything else (credential reveal, auth flows, uninstall/migration,
 * extension IPC, remote management itself) stays desktop-only.
 */
export const REMOTE_ALLOWED_INVOKE_CHANNELS: ReadonlySet<string> = new Set([
  // Core settings + runtime data plane.
  'settings:get',
  'settings:set',
  'settings:save-silent',
  'settings:open-config-file',
  'runtime:request',
  'runtime:request:cancel',
  'runtime:sse:start',
  'runtime:sse:stop',
  'runtime:sse:ack',
  'runtime:settings-sync-status:get',
  'shared-client-state:get',
  'shared-client-state:put',
  'startup:state:get',
  'app:version',
  'app:badge-count',
  'log:error',
  'log:get-path',
  'log:open-dir',
  'gateway:credential',
  'approval:decide',
  'room:permissions:set',
  'runtime:restart',
  'runtime:restart-serve',
  'upstream:models',
  'provider:probe',
  'provider:quota:list',
  'provider:models-dev-catalog',
  'prompt:optimize',
  'runtime:attachment:upload-image',
  'runtime:attachment:upload-document',
  'window:mini-mode:get',
  'notification:turn-complete',
  // Workspace selection + file operations.
  'workspace:directory-exists',
  'workspace:creation-times',
  'conversation:create-workspace',
  'file:list-workspace-directory',
  'file:resolve-workspace',
  'file:read-workspace',
  'file:write-workspace',
  'file:create-workspace',
  'file:create-workspace-directory',
  'file:rename-workspace-entry',
  'file:delete-workspace-entry',
  'file:watch-workspace',
  'file:unwatch-workspace',
  'file:read-workspace-image',
  'file:read-workspace-pdf',
  'file:open-workspace-preview',
  'file:release-workspace-preview',
  'file:save-workspace-clipboard-image',
  'file:save-workspace-image-bytes',
  'file:read-local-office-document',
  'file:read-workspace-office-preview',
  'file:read-workspace-office-semantic',
  'file:save-workspace-spreadsheet',
  'file:convert-workspace-spreadsheet',
  'file:read-local-pdf-text',
  'clipboard:read-image',
  // Git and worktrees.
  'git:branches',
  'git:switch-branch',
  'git:create-and-switch-branch',
  'git:checkpoint:create',
  'git:checkpoint:restore',
  'git:checkout-branch-worktree',
  'git:create-branch-worktree',
  'git:branch-worktrees',
  'git:remove-branch-worktree',
  'worktree:acquire',
  'worktree:release',
  'worktree:list',
  'worktree:remove',
  'worktree:changes',
  'worktree:commit',
  'worktree:merge',
  'worktree:abort-merge',
  'worktree:continue-merge',
  'worktree:sync',
  'worktree:abort-rebase',
  'worktree:cleanup',
  'worktree:find-available',
  // Local terminal + Remote SSH terminals.
  'terminal:create',
  'terminal:write',
  'terminal:resize',
  'terminal:dispose',
  'remote-ssh:hosts:list',
  'remote-ssh:hosts:create',
  'remote-ssh:hosts:update',
  'remote-ssh:hosts:remove',
  'remote-ssh:connect',
  'remote-ssh:disconnect',
  'remote-ssh:host-key:reset',
  'remote-ssh:host-key:confirm',
  'remote-ssh:terminal:create',
  'remote-ssh:terminal:write',
  'remote-ssh:terminal:resize',
  'remote-ssh:terminal:dispose',
  // Skills and Kun config files.
  'skill:list',
  'skill:list-roots',
  'skill:save-file',
  'skill:import-github',
  'skill:open-root',
  'kun:config:read',
  'kun:config:write',
  'kun:config:open-dir',
  'kun:project-config:read',
  'kun:project-config:write',
  'kun:project-config:trust',
  'kun:project-config:open-dir',
  // Claw / schedule / daemon / workflow runtimes.
  'claw:status',
  'claw:task:run',
  'claw:channel:mirror',
  'claw:channel:mirror-to-feishu',
  'claw:task:create-from-text',
  'schedule:status',
  'schedule:task:create',
  'schedule:task:update',
  'schedule:task:delete',
  'schedule:task:run',
  'schedule:task:create-from-text',
  'daemon:status',
  'daemon:restart',
  'daemon:logs',
  'workflow:status',
  'workflow:run',
  'workflow:stop',
  'workflow:node:run',
  'workflow:node:test',
  'workflow:approval:resolve',
  'workflow:code:check',
  // Legacy session import.
  'kun:sessions:detect-legacy',
  'kun:sessions:import-legacy',
  // UI plugins (read + theme activation only; install/remove stay local).
  'ui-plugin:list',
  'ui-plugin:load',
  'ui-plugin:theme:activate',
  'ui-plugin:theme:deactivate',
  // Editors and exports.
  'editor:list',
  'editor:open-path',
  'write:export',
  'write:copy-rich-text',
  'write:inline-completion',
  'write:retrieve-context',
  'write:read-document-sha256',
  'write:generate-infographic',
  'write:authorize-prototype',
  'write:open-prototype',
  'write:inline-completion-debug:list',
  'write:inline-completion-debug:clear',
  'conversation:export',
  'memory:export-markdown',
  'design:export-prototype',
  'design:lint-project-design-md',
  // Browser-use control surfaces (the browser runs on the host Runtime).
  'browser-use:state:get',
  'browser-use:mount',
  'browser-use:origin:decide',
  'browser-use:action:decide',
  'browser-use:control',
  'browser-use:navigate',
  'browser-use:stop',
  'browser-use:clear',
  'cli-install:status',
  'cli-install:action',
  'speech:transcribe',
  'gui:update-state'
])

/** Event channels a Remote client's sender stub may receive via send(). */
export const REMOTE_ALLOWED_EVENT_CHANNELS: ReadonlySet<string> = new Set([
  'runtime:sse-open',
  'runtime:sse-event',
  'runtime:sse-end',
  'runtime:sse-error',
  'file:workspace-changed',
  'terminal:data',
  'terminal:exit',
  'remote-ssh:terminal:data',
  'remote-ssh:terminal:exit',
  'browser-use:state'
])

/**
 * Broadcast channels mirrored from the main window's webContents.send to every
 * Remote client (status/activity pushes that are not owned by one sender).
 */
export const REMOTE_BROADCAST_EVENT_CHANNELS: ReadonlySet<string> = new Set([
  'runtime:status',
  'app:quitting',
  'runtime:settings-sync-status',
  'startup:state',
  'schedule:status-changed',
  'claw:channel-activity',
  'window:mini-mode',
  'gui:update-state',
  'claude-subscription:sdk-progress',
  'gemini-subscription:cli-progress',
  'speech:local-whisper:progress',
  'speak:sanotts:progress',
  'extension:view-session:invalidated',
  'extension:external-browser-state',
  'extension:view-event',
  'extension:composer-context-attached',
  'extension:notifications'
])
