/**
 * kun-pi-bridge — extension source written into the pi agent home at session
 * start (P6-10). Runs inside the pi subprocess; cannot import kun modules —
 * only pi's extension API, node:fs and node:path.
 *
 * Responsibilities:
 *  1. Permission gate on `tool_call`: mode is read fresh per call from
 *     KUN_PI_PERMISSION_FILE (`{"mode":"read-only"|"ask"|"auto"|"bypass"}`,
 *     missing/corrupt → 'ask' fail-closed) so host-side mode switches apply
 *     without respawning.
 *  2. Hard blocks independent of mode: structured writes into
 *     PI_CODING_AGENT_DIR (models.json / permission file / extensions are the
 *     control plane — a model-written models.json could MITM all traffic), and
 *     bash reads of /proc/<pid>/environ (side channel around secret env
 *     stripping).
 *  3. Asks route through `ctx.ui.input` ('kun:approval') → the host answers
 *     'allow' | 'deny' | 'cancel' via extension_ui_response. `input` (not
 *     `confirm`) so a deny/cancel distinction reaches the model honestly.
 */

export const KUN_PI_BRIDGE_FILENAME = 'kun-pi-bridge.ts'

const BRIDGE_SOURCE = `// <generated by kun — do not edit inside the pi agent home>
import * as fs from 'node:fs'
import * as path from 'node:path'

const PERMISSION_TITLE = 'kun:approval'
const READONLY_TOOLS = new Set(['read', 'grep', 'find', 'ls'])
const WRITE_TOOLS = new Set(['edit', 'write'])
const MAX_PERMISSION_FILE = 16 * 1024
const MAX_ASK_PAYLOAD = 64 * 1024

function readMode() {
  const file = process.env.KUN_PI_PERMISSION_FILE
  if (!file) return 'ask'
  try {
    const stat = fs.statSync(file)
    if (!stat.isFile() || stat.size > MAX_PERMISSION_FILE) return 'ask'
    const parsed = JSON.parse(fs.readFileSync(file, 'utf8'))
    const mode = parsed && typeof parsed.mode === 'string' ? parsed.mode : ''
    return ['read-only', 'ask', 'auto', 'bypass'].includes(mode) ? mode : 'ask'
  } catch {
    return 'ask'
  }
}

function isInsideRoot(target, root) {
  if (!target || !root) return false
  const rel = path.relative(path.resolve(root), path.resolve(target))
  return rel === '' || (!rel.startsWith('..') && !path.isAbsolute(rel))
}

// Literal path is not enough: a symlinked parent inside the agent home could
// still point outside. Resolve the target when it exists, otherwise resolve
// the nearest existing ancestor and re-append the basename.
function resolveTarget(target) {
  try {
    return fs.realpathSync(target)
  } catch {
    let dir = path.dirname(target)
    for (let i = 0; i < 64; i += 1) {
      try {
        return path.join(fs.realpathSync(dir), path.basename(target))
      } catch {
        const parent = path.dirname(dir)
        if (parent === dir) return null
        dir = parent
      }
    }
    return null
  }
}

function commandReadsEnviron(command) {
  return typeof command === 'string'
    && /\\/proc\\/(?:\\d+|self|\\*)\\/environ/.test(command)
}

export default async function kunPiBridge(pi) {
  pi.on('tool_call', async (event, ctx) => {
    const toolName = String(event && event.toolName ? event.toolName : '')
    const input = (event && event.input && typeof event.input === 'object')
      ? event.input : {}
    const mode = readMode()

    // Hard blocks (all modes, including bypass). Protected roots: the pi
    // agent home (models.json/auth.json/extension control plane) AND the
    // permission file's own directory — otherwise a model could rewrite the
    // permission file to 'bypass' and self-escalate.
    if (WRITE_TOOLS.has(toolName)) {
      const target = typeof input.path === 'string' ? input.path : ''
      const permissionFile = process.env.KUN_PI_PERMISSION_FILE
      const protectedRoots = [
        process.env.PI_CODING_AGENT_DIR,
        permissionFile ? path.dirname(permissionFile) : undefined,
      ].filter(Boolean)
      if (target) {
        const resolved = resolveTarget(target)
        const inside = protectedRoots.some((root) =>
          isInsideRoot(target, root)
          || (resolved && isInsideRoot(resolved, root)))
        if (inside) {
          return { block: true, reason: 'Kun agent control plane is read-only.' }
        }
      }
    }
    if (toolName === 'bash') {
      const command = typeof input.command === 'string' ? input.command : ''
      if (commandReadsEnviron(command)) {
        return {
          block: true,
          reason: 'Kun blocks reading process environment (/proc/*/environ).'
        }
      }
      // Heuristic (not an OS sandbox): a bash command naming a protected root
      // verbatim could overwrite models.json or the permission file. Models
      // can obfuscate paths — this catches the plain spellings; bypass mode
      // already trusts the model's code.
      const permissionFile = process.env.KUN_PI_PERMISSION_FILE
      const protectedRoots = [
        process.env.PI_CODING_AGENT_DIR,
        permissionFile ? path.dirname(permissionFile) : undefined,
      ].filter(Boolean)
      if (command && protectedRoots.some((root) => command.includes(root))) {
        return {
          block: true,
          reason: 'Kun agent control plane is read-only.'
        }
      }
    }

    if (mode === 'bypass') return
    if (mode === 'read-only') {
      if (READONLY_TOOLS.has(toolName)) return
      return {
        block: true,
        reason: 'Kun read-only mode only permits read/grep/find/ls.'
      }
    }
    if (mode === 'auto') return

    // mode === 'ask' (and fail-closed default): read-only builtins pass;
    // everything else asks the host.
    if (READONLY_TOOLS.has(toolName)) return
    let decision
    try {
      const payload = JSON.stringify({
        toolName,
        toolCallId: String(event.toolCallId ?? ''),
        input
      }).slice(0, MAX_ASK_PAYLOAD)
      decision = await ctx.ui.input(PERMISSION_TITLE, payload)
    } catch {
      decision = undefined
    }
    if (decision !== 'allow') {
      return {
        block: true,
        reason: decision === 'deny'
          ? 'User denied this tool call.'
          : 'Kun could not approve this tool call.'
      }
    }
  })
}
`

/** Extension source written to <agentHome>/extensions/kun-pi-bridge.ts. */
export function kunPiBridgeSource(): string {
  return BRIDGE_SOURCE
}
