/**
 * [INPUT]: 依赖 research/core、agents、evidence、runtime、storage、verification 的公开导出
 * [OUTPUT]: 对外提供 Kun DeepResearch 模块的统一 TypeScript barrel export
 * [POS]: research 模块边界，被 server routes、runtime factory 和测试消费
 * [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
 */
export * from './core/events.js'
export * from './core/hash.js'
export * from './core/comparison.js'
export * from './core/coverage.js'
export * from './core/presets.js'
export * from './core/question-contract.js'
export * from './core/report-argument.js'
export * from './core/report-closing.js'
export * from './core/scope-metadata.js'
export * from './core/scope-list.js'
export * from './core/state-machine.js'
export * from './core/types.js'
export * from './core/validation.js'
export * from './agents/GapAnalyzer.js'
export * from './agents/HypothesisAgent.js'
export * from './agents/PlanAgent.js'
export * from './agents/ReportArchitect.js'
export * from './agents/ResearchEditor.js'
export * from './agents/ResearchTaskWorker.js'
export * from './agents/ScopeAgent.js'
export * from './agents/SourceStrategist.js'
export * from './agents/SupervisorAgent.js'
export * from './agents/SynthesisWriter.js'
export * from './agents/types.js'
export * from './evidence/CitationResolver.js'
export * from './evidence/ClaimSupport.js'
export * from './evidence/EvidenceStore.js'
export * from './evidence/EvidenceEligibility.js'
export * from './evidence/types.js'
export * from './runtime/ResearchRuntime.js'
export * from './runtime/ResearchRuntimeService.js'
export * from './runtime/ResearchPreflightGate.js'
export * from './runtime/ResearchProgressGuard.js'
export * from './runtime/ResearchSourcePolicy.js'
export * from './runtime/ResearchWritableGate.js'
export * from './runtime/DefaultResearchTaskWorker.js'
export * from './runtime/DeepSeekWebSearchProvider.js'
export * from './runtime/BraveWebSearchProvider.js'
export * from './runtime/BingRssWebSearchProvider.js'
export * from './runtime/GenericWebSearchProvider.js'
export * from './runtime/YahooWebSearchProvider.js'
export * from './runtime/SearxngWebSearchProvider.js'
export * from './runtime/TavilyWebSearchProvider.js'
export * from './runtime/CascadingWebSearchProvider.js'
export * from './runtime/ModelResearchTaskWorker.js'
export * from './runtime/SeededWebResearchTaskWorker.js'
export * from './storage/ResearchRunRepository.js'
export * from './verification/QualityJudge.js'
export * from './verification/ReportPublicationSafety.js'
export * from './verification/QualityVerifier.js'
