import type { RuntimeRequestResult } from './kun-gui-api-contracts'

export type KunProtectedApprovalRequest = {
  presentation?: 'room'
  approvalId: string
  decision: 'allow' | 'deny'
  /** Policy decisions are generated by Kun; user decisions require a protected native confirmation. */
  source: 'policy' | 'user'
}

export type KunProtectedApprovalResult =
  | { confirmed: false }
  | { confirmed: true; response: RuntimeRequestResult }

export type RoomPermissionChange = import('./rooms-api').RoomPermissionRequest & { roomId: string }
export type RoomPermissionChangeResult = { confirmed: false } | { confirmed: true; state: import('./rooms-api').RoomPermissionState }
