import { describe, expect, it } from 'vitest'
import {
  ClientFrameSchema,
  InvitationBundleSchema,
  ServerEventSchema,
  SignedReceiptSchema
} from './schema.js'

const encrypted = {
  algorithm: 'mls' as const,
  ciphertext: Buffer.from('opaque ciphertext').toString('base64'),
  contentType: 'application/vnd.kun.collaboration-event+json',
  plaintextBytes: 128,
  sha256: 'a'.repeat(64),
  epoch: 3
}

describe('collaboration protocol v1', () => {
  it('parses a versioned encrypted command frame', () => {
    expect(ClientFrameSchema.parse({
      version: 1,
      kind: 'command',
      commandId: 'command-1',
      meetingId: 'meeting-1',
      expectedVersion: 4,
      payload: encrypted
    })).toMatchObject({ kind: 'command', version: 1 })
  })

  it('accepts only the human collaboration event namespace', () => {
    expect(() => ServerEventSchema.parse({
      version: 1,
      kind: 'collaboration_task_created',
      meetingId: 'meeting-1',
      sequence: 1,
      epoch: 3,
      payload: encrypted,
      receipt: receipt()
    })).toThrow()
    expect(ServerEventSchema.parse({
      version: 1,
      kind: 'human_task_created',
      meetingId: 'meeting-1',
      sequence: 1,
      epoch: 3,
      payload: encrypted,
      receipt: receipt()
    })).toMatchObject({ kind: 'human_task_created', sequence: 1 })
  })

  it('rejects oversized ciphertext before transport', () => {
    expect(() => ClientFrameSchema.parse({
      version: 1,
      kind: 'command',
      commandId: 'command-large',
      meetingId: 'meeting-1',
      expectedVersion: 1,
      payload: { ...encrypted, ciphertext: 'A'.repeat(1_500_000) }
    })).toThrow()
  })

  it('requires bounded one-time invitations and signed receipts', () => {
    expect(InvitationBundleSchema.parse({
      version: 1,
      invitationId: 'invite-1',
      serverUrl: 'https://collab.example.test',
      serverInstanceId: 'server-1',
      spkiSha256: 'b'.repeat(64),
      meetingId: 'meeting-1',
      oneTimeCredential: Buffer.from('secret').toString('base64'),
      expiresAt: '2026-07-18T00:00:00.000Z'
    })).toMatchObject({ invitationId: 'invite-1' })
    expect(SignedReceiptSchema.parse(receipt())).toMatchObject({ commandId: 'command-1' })
  })

  it('accepts unpadded Base64URL credentials generated by native and Node clients', () => {
    expect(InvitationBundleSchema.parse({
      version: 1,
      invitationId: 'invite-url-safe',
      serverUrl: 'https://collab.example.test',
      serverInstanceId: 'server-1',
      spkiSha256: 'b'.repeat(64),
      meetingId: 'meeting-1',
      oneTimeCredential: 'ab-cd_ef0123456789ABCD',
      expiresAt: '2026-07-18T00:00:00.000Z'
    })).toMatchObject({ invitationId: 'invite-url-safe' })
  })
})

function receipt() {
  return {
    commandId: 'command-1',
    meetingId: 'meeting-1',
    sequence: 1,
    acceptedAt: '2026-07-17T00:00:00.000Z',
    serverInstanceId: 'server-1',
    signature: Buffer.from('signature').toString('base64')
  }
}
