export type SettingsRouteSection =
  | 'general'
  | 'providers'
  | 'extensions'
  | 'write'
  | 'design'
  | 'imageGeneration'
  | 'mediaGeneration'
  | 'speechToText'
  | 'agents'
  | 'laboratory'
  | 'subagents'
  | 'archives'
  | 'worktree'
  | 'memory'
  | 'permissions'
  | 'skill'
  | 'mcp'
  | 'shortcuts'
  | 'easterEgg'
  | 'claw'
  | 'updates'
  | 'terminal'
  | 'debug'
  | 'storage'
  | 'dataMigration'

export type AppRoute =
  | 'chat'
  | 'write'
  | 'design'
  | 'settings'
  | 'plugins'
  | 'extensions'
  | 'claw'
  | 'board'
  | 'schedule'
  | 'workflow'
  | 'nodeGraph'

export type PluginHostRoute = 'chat' | 'claw'
