'use strict'
const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const { join } = require('node:path')
const test = require('node:test')
const { parse } = require('yaml')
const root = join(__dirname, '..')
const source = (file) => readFileSync(join(root, file), 'utf8')

test('private workspace smoke is required on native macOS and Windows for relevant changes', () => {
  const workflow = parse(source('.github/workflows/personal-agent-workspace-smoke.yml'))
  assert.ok(Object.hasOwn(workflow.on, 'workflow_dispatch'))
  for (const path of ['src/main/browser-use/**', 'src/renderer/src/components/rooms/**',
    'kun/src/agents/agent-direct*', 'kun/src/agents/agent-artifact*', 'src/shared/browser-use.ts',
    'scripts/smoke-personal-agent-workspace*', 'scripts/smoke-direct-model*',
    'scripts/personal-agent-workspace-workflow.test.cjs', '.github/workflows/personal-agent-workspace-smoke.yml']) {
    assert.ok(workflow.on.pull_request.paths.includes(path), path)
  }
  assert.deepEqual(workflow.permissions, { contents: 'read' })
  const job = workflow.jobs['native-workspace']
  assert.deepEqual(job.strategy.matrix.os, ['macos-latest', 'windows-latest'])
  assert.equal(job['runs-on'], '${{ matrix.os }}')
  assert.equal(job.if, undefined)
  assert.equal(job['continue-on-error'], undefined)
  assert(job['timeout-minutes'] > 10)
  assert(job.steps.every((step) => step['continue-on-error'] === undefined))
  const commands = job.steps.map((step) => step.run)
  const smoke = commands.findIndex((command) => command?.includes('--personal-workspace-only'))
  const ensure = commands.indexOf('npm run ensure:electron')
  const build = commands.indexOf('npm run build')
  assert(ensure >= 0 && build >= 0 && smoke > ensure && smoke > build)
  assert.equal(job.steps[smoke].if, undefined)
  assert.equal(job.steps[smoke]['timeout-minutes'], 10)
  assert(commands.some((command) => command?.includes('scripts/personal-agent-workspace-workflow.test.cjs')))
  const runtime = job.steps.find((step) => step['working-directory'] === 'kun')
  assert.match(runtime.run, /agent-direct-execution\.test\.ts/)
  assert.match(runtime.run, /agent-artifact-source\.test\.ts/)
  assert(commands.some((command) => command?.includes('network-policy.test.ts')))
  assert(commands.some((command) => command?.includes('AgentBrowserPanel.lifecycle.test.ts')))
  const upload = job.steps.find((step) => step.uses === 'actions/upload-artifact@v4')
  assert.equal(upload.if, 'always()')
  assert.equal(upload.with.path, 'dist/personal-agent-workspace-smoke')
  assert.match(upload.with.name, /matrix.os/)
  assert.doesNotMatch(commands.filter(Boolean).join('\n'), /--real-model|--no-sandbox|--disable-web-security|continue-on-error/)
})

test('workspace harness keeps existing native sandbox and labels fixture boundaries explicitly', () => {
  const harness = source('scripts/smoke-development-direct-chat.cjs')
  const smoke = source('scripts/smoke-personal-agent-workspace.cjs')
  assert.match(harness, /--personal-workspace-only.*exercisePersonalAgentWorkspace/)
  assert.match(harness, /chromiumSandbox: true/)
  assert.match(harness, /mode: 'local-development'/)
  assert.match(harness, /Personal workspace evidence must stay offline/)
  assert(harness.indexOf('Personal workspace evidence must stay offline') < harness.indexOf('modelFixture = await startDirectModel'))
  assert.match(smoke, /await originButton\.click\(\)/)
  assert.match(smoke, /No page request occurs before exact-origin consent/)
  assert.match(smoke, /contents\.capturePage\(\)/)
  assert.match(smoke, /window\.kunGui\.restartKunServe\(\)/)
  assert.match(smoke, /mainCalls, callsBeforeRestart/)
  assert.match(smoke, /one exact native Runtime restart confirmation response/)
  for (const label of ['Take control', 'Return to agent', 'Stop', 'Show current browser']) assert(smoke.includes(`name: '${label}', exact: true`), label)
  assert.doesNotMatch(smoke, /__.*Browser.*Fixture|BrowserUseViewState|Object\.defineProperty\(window, 'kunGui'/)
})


test('native workspace smoke uses ordinary collapse and reopen without forcing composer controls', () => {
  const smoke = source('scripts/smoke-personal-agent-workspace.cjs')
  assert.match(smoke, /name: 'Collapse right sidebar', exact: true/)
  assert.match(smoke, /collapsed browser is no longer visible/)
  const stopped = smoke.indexOf("await capture('workspace-15b-browser-stopped')")
  const collapse = smoke.indexOf('await collapseWorkspacePanel(active.threadId)', stopped)
  const click = smoke.indexOf("name: 'Stop response', exact: true", collapse)
  const cancelled = smoke.indexOf("'durable response cancellation'", click)
  const reopen = smoke.indexOf('await openBrowser()', cancelled)
  const detached = smoke.indexOf("await capture('workspace-16-stopped-browser-detached')", reopen)
  assert(stopped >= 0 && collapse > stopped && click > collapse && cancelled > click && reopen > cancelled && detached > reopen)
  assert.match(smoke, /const send = async \(text\) => \{[\s\S]*?await collapseWorkspacePanel\(\)[\s\S]*?await editor\(\)\.fill\(text\)/)
  assert.doesNotMatch(smoke, /force:\s*true|dispatchEvent\(|evaluate\([^\n]*click/)
})
