import { useState } from 'react'
import { RefreshCw, Send, Square } from 'lucide-react'
import type { EmployeeInvocation, ReceptionEmployeePublication } from '@shared/collaboration/contracts'
import { useCollaborationStore } from './collaboration-store'

export function ReceptionEmployeeDetail({ employee, invocations }: { employee: ReceptionEmployeePublication; invocations: EmployeeInvocation[] }): React.ReactElement {
  const { dispatch, dispatchNetwork, networkLoading } = useCollaborationStore()
  const [prompt, setPrompt] = useState('')
  const invoke = async () => { if (!prompt.trim()) return; await dispatch({ kind: 'employee_invoke', employeeId: employee.employeeId, prompt: prompt.trim(), meetingId: employee.meetingIds[0] }); setPrompt('') }
  return <div className="flex h-full min-h-0 flex-col bg-ds-main p-6 text-ds-text"><header className="mb-5 flex items-start gap-3"><div className="min-w-0 flex-1"><h1 className="text-lg font-semibold">{employee.displayName}</h1><p className="mt-1 text-[12px] text-ds-muted">{employee.description}</p><div className="mt-2 text-[11px] text-ds-muted">授权工具：{employee.allowedToolNames.join(', ') || '无'}</div></div>{employee.meetingIds[0] ? <button type="button" onClick={() => void dispatchNetwork({ kind: 'network_sync', meetingId: employee.meetingIds[0] })} aria-label="同步远程调用" title="同步远程调用" className="inline-flex h-8 w-8 items-center justify-center rounded-md border border-ds-border-muted"><RefreshCw className={`h-3.5 w-3.5 ${networkLoading ? 'animate-spin' : ''}`} /></button> : null}</header><div className="flex gap-2"><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} rows={3} placeholder="输入需要数字员工处理的任务" className="min-w-0 flex-1 rounded-md border border-ds-border-muted bg-ds-card px-3 py-2 text-[13px]" /><button type="button" onClick={() => void invoke()} disabled={!prompt.trim()} aria-label="调用数字员工" title="调用数字员工" className="inline-flex h-10 w-10 items-center justify-center rounded-md bg-accent text-white disabled:opacity-40"><Send className="h-4 w-4" /></button></div><section className="mt-6 min-h-0 flex-1 overflow-y-auto"><h2 className="mb-2 text-[13px] font-medium">调用记录</h2>{invocations.map((invocation) => <div key={invocation.id} className="flex items-start gap-3 border-b border-ds-border-muted py-3"><div className="min-w-0 flex-1"><div className="text-[12px]">{invocation.prompt}</div><div className="mt-1 text-[11px] text-ds-muted">{invocation.status}{invocation.resultSummary ? ` · ${invocation.resultSummary}` : ''}</div></div>{!['completed', 'failed', 'interrupted'].includes(invocation.status) ? <button type="button" onClick={() => void dispatch({ kind: 'employee_interrupt', invocationId: invocation.id })} aria-label="中断调用" title="中断调用" className="inline-flex h-8 w-8 items-center justify-center rounded-md border border-ds-border-muted"><Square className="h-3.5 w-3.5" /></button> : null}</div>)}{invocations.length === 0 ? <div className="py-8 text-center text-[12px] text-ds-muted">暂无调用记录</div> : null}</section></div>
}
